Add collapsible panel abstract class for terrier-engine
Terrier-Tech/terrier-engine pull request #134
Opened 2023-07-26 15:18 UTC by last-starset

2023-07-27 16:24 UTC, mswerdal approved these changes
Looks good to me. Just some questions:

1. Why's `childInit` necessary?
2. Did you test this on the terrier-engine demo page? Or somewhere in Clypboard/Hub?
3. Have you checked whether @schultzcole wants this in Terrier Engine or Hub?
4. When @schultzcole requested a new type of panel, did he mean an entirely new part? Or just to adapt the existing PanelPart to support a chevron. I think either is fine, but I'd like to know his preference.

2023-07-27 16:24 UTC, mswerdal commented on app/frontend/terrier/parts/collapsible-panel-part.ts
> +    abstract childInit(): Promise<void>
What's this used for? (`childInit`)

2023-07-27 17:02 UTC, last-starset commented
My understanding is that if a child class has an init() function, it'll overwrite the parent's init() function. I did feel weird about it and would absolutely love to do it some more elegant way. 
I tested it in Hub but I want to address the styling issues in terrier-engine. I agree that that's off. 
Cole wants this in Terrier Engine. It was my understanding that he wanted a new part that was a panel, but collapsible. I can ask him about which one.

2023-07-31 17:13 UTC, mswerdal requested changes
Summary of my recommendations:

1. The collapse key doesn't need to be typed, does it?
2. With the code as it was written, passing `collapsible: false` in state would've still created a collapsible panel. I've included a potential solution to this (`PanelState`), but please check that this makes sense with Cole. I like this since it removes the need for local variables (lines 11-14). Cole requested a similar change when I did the reactions feature.
3. We probably want to handle clicks on the header itself, rather than the chevron div.
4. Potentially investigate whether we can/should do anything about this gap (assuming you haven't written any style for it in The Hub):

![CleanShot 2023-07-31 at 12 17 47](https://github.com/Terrier-Tech/terrier-engine/assets/25541844/f5530f49-8cd0-4118-aa16-864ecfbf71ef)

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
```suggestion
type PanelState = {
    collapsed?: Boolean
    collapsible?: Boolean
    chevronSide?: string
}
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +        }
```suggestion
        if (!this.state.chevronSide) {
            this.state.chevronSide = 'left'
        }
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +                    if (this.chevronSide == 'left') {
```suggestion
                    if (this.state.chevronSide == 'left') {
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +                    if (this.chevronSide == 'right') {
```suggestion
                    if (this.state.chevronSide == 'right') {
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +            if (!this.collapsed) {
```suggestion
            if (!this.state.collapsed) {
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +        this.collapsed = !this.collapsed
```suggestion
        this.state.collapsed = !this.state.collapsed
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +        if (this.collapsible) {
```suggestion
        if (this.state.collapsible) {
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +                if (this.collapsed) {
```suggestion
                if (this.state.collapsed) {
```

2023-07-31 17:13 UTC, mswerdal commented on app/frontend/terrier/parts/panel-part.ts
> +                chev.emitClick(this.toggleCollapseKey, {})
Toggle whenever **header** is clicked, instead of just the chevron.
```suggestion
                parent.emitClick(this.toggleCollapseKey)
```

2023-08-01 01:19 UTC, mswerdal approved these changes

2023-08-01 13:00 UTC, merged